import Plyr from 'plyr'
import i18n from '@/i18n'
import 'plyr/dist/plyr.css'
import '@/assets/styles/plyr.less'

const locales = {
  'zh-CN': {
    restart: '重新播放',
    rewind: '倒退 {seektime} 秒',
    play: '播放',
    pause: '暂停',
    fastForward: '快进 {seektime} 秒',
    seek: '搜索',
    seekLabel: '{currentTime} / {duration}',
    played: '已播放',
    buffered: '已缓冲',
    currentTime: '当前时间',
    duration: '持续时间',
    volume: '音量',
    mute: '静音',
    unmute: '取消静音',
    enableCaptions: '启用字幕',
    disableCaptions: '禁用字幕',
    download: '下载',
    enterFullscreen: '进入全屏',
    exitFullscreen: '退出全屏',
    captions: '字幕',
    settings: '设置',
    pip: '画中画',
    menuBack: '返回',
    seek: '播放位置',
    speed: '速度',
    normal: '正常',
    quality: '质量',
    loop: '循环',
    start: '开始',
    end: '结束',
    all: '全部',
    reset: '重置',
    disabled: '已禁用',
    enabled: '已启用',
  },
  'en-US': {
    restart: 'Restart',
    rewind: 'Rewind {seektime}s',
    play: 'Play',
    pause: 'Pause',
    fastForward: 'Forward {seektime}s',
    seek: 'Seek',
    seekLabel: '{currentTime} of {duration}',
    played: 'Played',
    buffered: 'Buffered',
    currentTime: 'Current time',
    duration: 'Duration',
    volume: 'Volume',
    mute: 'Mute',
    unmute: 'Unmute',
    enableCaptions: 'Enable captions',
    disableCaptions: 'Disable captions',
    download: 'Download',
    enterFullscreen: 'Enter fullscreen',
    exitFullscreen: 'Exit fullscreen',
    frameTitle: 'Player for {title}',
    captions: 'Captions',
    settings: 'Settings',
    pip: 'PIP',
    menuBack: 'Go back to previous menu',
    speed: 'Speed',
    normal: 'Normal',
    quality: 'Quality',
    loop: 'Loop',
    start: 'Start',
    end: 'End',
    all: 'All',
    reset: 'Reset',
    disabled: 'Disabled',
    enabled: 'Enabled',
  },
  'ar-KSA': {
    restart: 'إعادة التشغيل',
    rewind: 'الرجوع {seektime} ثانية',
    play: 'تشغيل',
    pause: 'إيقاف مؤقت',
    fastForward: 'التقديم {seektime} ثانية',
    seek: 'البحث',
    seekLabel: '{currentTime} من {duration}',
    played: 'تم التشغيل',
    buffered: 'تم التخزين المؤقت',
    currentTime: 'الوقت الحالي',
    duration: 'المدة',
    volume: 'الصوت',
    mute: 'كتم الصوت',
    unmute: 'إلغاء كتم الصوت',
    enableCaptions: 'تمكين الترجمة',
    disableCaptions: 'تعطيل الترجمة',
    download: 'تحميل',
    enterFullscreen: 'دخول الشاشة الكاملة',
    exitFullscreen: 'الخروج من الشاشة الكاملة',
    frameTitle: 'مشغل {title}',
    captions: 'الترجمة',
    settings: 'الإعدادات',
    pip: 'صورة في صورة',
    menuBack: 'العودة للقائمة السابقة',
    speed: 'السرعة',
    normal: 'عادي',
    quality: 'الجودة',
    loop: 'تكرار',
    start: 'البداية',
    end: 'النهاية',
    all: 'الكل',
    reset: 'إعادة تعيين',
    disabled: 'معطل',
    enabled: 'مفعل',
  },
  'ja-JP': {
    restart: '再開',
    rewind: '{seektime}秒戻る',
    play: '再生',
    pause: '一時停止',
    fastForward: '{seektime}秒進む',
    seek: 'シーク',
    seekLabel: '{currentTime} / {duration}',
    played: '再生済み',
    buffered: 'バッファ済み',
    currentTime: '現在時刻',
    duration: '長さ',
    volume: '音量',
    mute: 'ミュート',
    unmute: 'ミュート解除',
    enableCaptions: '字幕を有効にする',
    disableCaptions: '字幕を無効にする',
    download: 'ダウンロード',
    enterFullscreen: 'フルスクリーン',
    exitFullscreen: 'フルスクリーン終了',
    frameTitle: '{title}のプレイヤー',
    captions: '字幕',
    settings: '設定',
    pip: 'ピクチャーインピクチャー',
    menuBack: '前のメニューに戻る',
    speed: '速度',
    normal: '標準',
    quality: '画質',
    loop: 'ループ',
    start: '開始',
    end: '終了',
    all: 'すべて',
    reset: 'リセット',
    disabled: '無効',
    enabled: '有効',
  },
  'ur-IN': {
    restart: 'دوبارہ شروع',
    rewind: '{seektime} سیکنڈ پیچھے',
    play: 'چلائیں',
    pause: 'روکیں',
    fastForward: '{seektime} سیکنڈ آگے',
    seek: 'تلاش',
    seekLabel: '{currentTime} کا {duration}',
    played: 'چلایا گیا',
    buffered: 'بفر ہوا',
    currentTime: 'موجودہ وقت',
    duration: 'مدت',
    volume: 'آواز',
    mute: 'خاموش',
    unmute: 'آواز آن',
    enableCaptions: 'ذیلی عنوانات آن',
    disableCaptions: 'ذیلی عنوانات آف',
    download: 'ڈاؤن لوڈ',
    enterFullscreen: 'مکمل اسکرین',
    exitFullscreen: 'مکمل اسکرین سے باہر',
    frameTitle: '{title} کا پلیئر',
    captions: 'ذیلی عنوانات',
    settings: 'سیٹنگز',
    pip: 'تصویر میں تصویر',
    menuBack: 'پچھلے مینو پر واپس',
    speed: 'رفتار',
    normal: 'عام',
    quality: 'معیار',
    loop: 'دہرائیں',
    start: 'شروع',
    end: 'اختتام',
    all: 'تمام',
    reset: 'دوبارہ سیٹ',
    disabled: 'بند',
    enabled: 'چالو',
  },
  'hi-IN': {
    restart: 'पुनः आरंभ',
    rewind: '{seektime} सेकंड पीछे',
    play: 'चलाएं',
    pause: 'रोकें',
    fastForward: '{seektime} सेकंड आगे',
    seek: 'खोजें',
    seekLabel: '{currentTime} का {duration}',
    played: 'चलाया गया',
    buffered: 'बफर हुआ',
    currentTime: 'वर्तमान समय',
    duration: 'अवधि',
    volume: 'आवाज़',
    mute: 'मौन',
    unmute: 'आवाज़ चालू',
    enableCaptions: 'उपशीर्षक चालू करें',
    disableCaptions: 'उपशीर्षक बंद करें',
    download: 'डाउनलोड',
    enterFullscreen: 'पूरी स्क्रीन',
    exitFullscreen: 'पूरी स्क्रीन से बाहर',
    frameTitle: '{title} का प्लेयर',
    captions: 'उपशीर्षक',
    settings: 'सेटिंग्स',
    pip: 'तस्वीर में तस्वीर',
    menuBack: 'पिछले मेनू में वापस',
    speed: 'गति',
    normal: 'सामान्य',
    quality: 'गुणवत्ता',
    loop: 'दोहराएं',
    start: 'शुरू',
    end: 'अंत',
    all: 'सभी',
    reset: 'रीसेट',
    disabled: 'बंद',
    enabled: 'चालू',
  },
  'kn-IN': {
    restart: '[ಕನ್ನಡ Restart]',
    rewind: '[ಕನ್ನಡ Rewind {seektime}s]',
    play: '[ಕನ್ನಡ Play]',
    pause: '[ಕನ್ನಡ Pause]',
    fastForward: '[ಕನ್ನಡ Forward {seektime}s]',
    seek: '[ಕನ್ನಡ Seek]',
    seekLabel: '[ಕನ್ನಡ {currentTime} of {duration}]',
    played: '[ಕನ್ನಡ Played]',
    buffered: '[ಕನ್ನಡ Buffered]',
    currentTime: '[ಕನ್ನಡ Current time]',
    duration: '[ಕನ್ನಡ Duration]',
    volume: '[ಕನ್ನಡ Volume]',
    mute: '[ಕನ್ನಡ Mute]',
    unmute: '[ಕನ್ನಡ Unmute]',
    enableCaptions: '[ಕನ್ನಡ Enable captions]',
    disableCaptions: '[ಕನ್ನಡ Disable captions]',
    download: '[ಕನ್ನಡ Download]',
    enterFullscreen: '[ಕನ್ನಡ Enter fullscreen]',
    exitFullscreen: '[ಕನ್ನಡ Exit fullscreen]',
    frameTitle: '[ಕನ್ನಡ Player for {title}]',
    captions: '[ಕನ್ನಡ Captions]',
    settings: '[ಕನ್ನಡ Settings]',
    pip: '[ಕನ್ನಡ PIP]',
    menuBack: '[ಕನ್ನಡ Go back to previous menu]',
    speed: '[ಕನ್ನಡ Speed]',
    normal: '[ಕನ್ನಡ Normal]',
    quality: '[ಕನ್ನಡ Quality]',
    loop: '[ಕನ್ನಡ Loop]',
    start: '[ಕನ್ನಡ Start]',
    end: '[ಕನ್ನಡ End]',
    all: '[ಕನ್ನಡ All]',
    reset: '[ಕನ್ನಡ Reset]',
    disabled: '[ಕನ್ನಡ Disabled]',
    enabled: '[ಕನ್ನಡ Enabled]',
  },
  'ta-IN': {
    restart: '[தமிழ் Restart]',
    rewind: '[தமிழ் Rewind {seektime}s]',
    play: '[தமிழ் Play]',
    pause: '[தமிழ் Pause]',
    fastForward: '[தமிழ் Forward {seektime}s]',
    seek: '[தமிழ் Seek]',
    seekLabel: '[தமிழ் {currentTime} of {duration}]',
    played: '[தமிழ் Played]',
    buffered: '[தமிழ் Buffered]',
    currentTime: '[தமிழ் Current time]',
    duration: '[தமிழ் Duration]',
    volume: '[தமிழ் Volume]',
    mute: '[தமிழ் Mute]',
    unmute: '[தமிழ் Unmute]',
    enableCaptions: '[தமிழ் Enable captions]',
    disableCaptions: '[தமிழ் Disable captions]',
    download: '[தமிழ் Download]',
    enterFullscreen: '[தமிழ் Enter fullscreen]',
    exitFullscreen: '[தమிழ் Exit fullscreen]',
    frameTitle: '[தமிழ் Player for {title}]',
    captions: '[தமிழ் Captions]',
    settings: '[தமிழ் Settings]',
    pip: '[தமிழ் PIP]',
    menuBack: '[தமிழ் Go back to previous menu]',
    speed: '[தமிழ் Speed]',
    normal: '[தமிழ் Normal]',
    quality: '[தமிழ் Quality]',
    loop: '[தமிழ் Loop]',
    start: '[தமிழ் Start]',
    end: '[தமிழ் End]',
    all: '[தமிழ் All]',
    reset: '[தமிழ் Reset]',
    disabled: '[தமிழ் Disabled]',
    enabled: '[தமிழ் Enabled]',
  },
  'te-IN': {
    restart: 'మళ్లీ ప్రారంభించు',
    rewind: '{seektime} సెకండ్లు వెనుకకు',
    play: 'ప్లే చేయి',
    pause: 'పాజ్ చేయి',
    fastForward: '{seektime} సెకండ్లు ముందుకు',
    seek: 'వెతుకు',
    seekLabel: '{currentTime} లో {duration}',
    played: 'ప్లే అయ్యింది',
    buffered: 'బఫర్ అయ్యింది',
    currentTime: 'ప్రస్తుత సమయం',
    duration: 'వ్యవధి',
    volume: 'వాల్యూం',
    mute: 'మ్యూట్',
    unmute: 'అన్మ్యూట్',
    enableCaptions: 'క్యాప్షన్లను ప్రారంభించు',
    disableCaptions: 'క్యాప్షన్లను నిలిపివేయి',
    download: 'డౌన్లోడ్',
    enterFullscreen: 'పూర్తి స్క్రీన్',
    exitFullscreen: 'పూర్తి స్క్రీన్ నుండి నిష్క్రమించు',
    frameTitle: '{title} కోసం ప్లేయర్',
    captions: 'క్యాప్షన్లు',
    settings: 'సెట్టింగ్లు',
    pip: 'పిక్చర్ ఇన్ పిక్చర్',
    menuBack: 'మునుపటి మెనుకు తిరిగి వెళ్లు',
    speed: 'వేగం',
    normal: 'సాధారణ',
    quality: 'నాణ్యత',
    loop: 'లూప్',
    start: 'ప్రారంభం',
    end: 'ముగింపు',
    all: 'అన్ని',
    reset: 'రీసెట్',
    disabled: 'అచేతనం',
    enabled: 'చేతనం',
  },
  'sp-SPA': {
    restart: 'Reiniciar',
    rewind: 'Retroceder {seektime}s',
    play: 'Reproducir',
    pause: 'Pausar',
    fastForward: 'Avanzar {seektime}s',
    seek: 'Buscar',
    seekLabel: '{currentTime} de {duration}',
    played: 'Reproducido',
    buffered: 'En búfer',
    currentTime: 'Tiempo actual',
    duration: 'Duración',
    volume: 'Volumen',
    mute: 'Silenciar',
    unmute: 'Activar sonido',
    enableCaptions: 'Activar subtítulos',
    disableCaptions: 'Desactivar subtítulos',
    download: 'Descargar',
    enterFullscreen: 'Pantalla completa',
    exitFullscreen: 'Salir de pantalla completa',
    frameTitle: 'Reproductor para {title}',
    captions: 'Subtítulos',
    settings: 'Configuración',
    pip: 'Picture-in-Picture',
    menuBack: 'Volver al menú anterior',
    speed: 'Velocidad',
    normal: 'Normal',
    quality: 'Calidad',
    loop: 'Repetir',
    start: 'Inicio',
    end: 'Fin',
    all: 'Todo',
    reset: 'Restablecer',
    disabled: 'Deshabilitado',
    enabled: 'Habilitado',
  },
}

export const mediaPlayer = (container) => {
  return new Plyr(container, {
    i18n: locales[i18n.global.locale.value],
    settings: [],
    tooltips: { controls: true },
    storage: { key: 'umo-editor:player' },
    disableContextMenu: false,
  })
}
